# Permalinks
permalink: /:year-:month-:day/:title

# Setup
title: Yeolam Sung
baseurl: ''
url: 'https://www.developersung13.com'

# Assets
sass:
  sass_dir: _sass
  style: :compressed

# Build settings
markdown: kramdown

# About
author:
  name: developersung
  url: https://developersung13.com/
  email: developersung13
  github: developersung13
  twitter: developersung

# Custom vars
version: 3.4.1
github:
  repo: https://github.com/developersung13/developersung13.github.io
